Fix incorrect exception handling in ``_PyModule_IsPossiblyShadowing``
